### ISSUE TITLE
Build Error with getCustomLibraryExtension()

### ISSUE THREAD

**Issue by acxz** [joaoleal/CppADCodeGen#53] opened 2020-03-17 21:26 UTC
```
/usr/include/cppad/cg/model/dynamic_lib/dynamic_library_processor.hpp: In member function ‘const string* CppAD::cg::DynamicModelLibraryProcessor<Base>::getCustomLibraryExtension() const’:
/usr/include/cppad/cg/model/dynamic_lib/dynamic_library_processor.hpp:84:16: error: cannot convert ‘const std::unique_ptr<const std::__cxx11::basic_string<char> >’ to ‘const string*’ {aka ‘const std::__cxx11::basic_string<char>*’} in return
   84 |         return _customLibExtension;
      |                ^~~~~~~~~~~~~~~~~~~
      |                |
      |                const std::unique_ptr<const std::__cxx11::basic_string<char> >
```
OS: ArchLinux
GCC: 9.3.0
CppAD: 20200000.2

**Comment by joaoleal** [comment] 2020-03-17 23:30
This is a duplicate of #52 .

**Comment by acxz** [comment] 2020-03-18 01:12
Ah pardon me for being too hasty, I'll go ahead and close the issue and the PR. When can we expect this change to be released in master or a new release? (It is build breaking for me rn)

**Closed** 2020-03-18 01:31 UTC
Labels: Duplicate
